//! Startup health: what degraded, whether the tray is actually visible, and how the app
//! stays reachable when it is not.
//!
//! This module exists because of issue #5 — a machine where Lumen ran with two processes and
//! no menu-bar icon. Both windows start hidden and the tray is the whole interface, so there
//! was no popover, no window, and no way to reach the fault reporter to report it.
//!
//! Two things made that undiagnosable rather than merely broken:
//!
//! 1. The logger was registered under `cfg!(debug_assertions)`, so in a released build every
//!    `log::error!` went to a no-op sink. The CHANGELOG and a comment on the issue both asked
//!    the reporter for a line from a log file that could not exist. See `log_level_from`.
//! 2. `TrayIconBuilder::build()` returning `Ok` was treated as "the icon is on screen". It is
//!    not the same claim. macOS persists a status item's removal into the app's own
//!    preferences, and on every later launch AppKit creates the item and immediately hides
//!    it — build succeeds, nothing is logged, and the fallback never fires. See
//!    `keys_to_clear` and `classify_presence`.
//!
//! Everything here is a pure function over injected inputs, deliberately. The parts that need
//! a live `AppHandle` and a real menu bar cannot be unit-tested at all (the same constraint
//! documented for autostart in `setup.rs`), so the decisions are separated from the effects
//! and the decisions are what carry tests.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Mutex;

/// What the log level should be, given `LUMEN_LOG` and the build profile.
///
/// Release defaults to `Warn` rather than off. An opt-in flag would be worthless for the case
/// this exists for: a user who cannot reach the app cannot be told to set an env var, and by
/// the time they are asked, the launch that mattered is over. Every tray and startup line is
/// logged at `warn!` or above so the diagnostic lands on the *first* bad launch.
pub fn log_level_from(env: Option<&str>, debug: bool) -> log::LevelFilter {
    let default = if debug {
        log::LevelFilter::Info
    } else {
        log::LevelFilter::Warn
    };
    let Some(raw) = env else { return default };
    match raw.trim().to_ascii_lowercase().as_str() {
        "off" => log::LevelFilter::Off,
        "error" => log::LevelFilter::Error,
        "warn" | "warning" => log::LevelFilter::Warn,
        "info" => log::LevelFilter::Info,
        "debug" => log::LevelFilter::Debug,
        "trace" => log::LevelFilter::Trace,
        // Unparseable falls back rather than erroring: a typo in an env var must not change
        // whether the app starts, and silently logging nothing is the worse failure.
        _ => default,
    }
}

/// Which `NSStatusItem Visible …` preference keys are suppressing our status item.
///
/// Compiled everywhere so its tests run everywhere — the decision is pure and worth checking on
/// any host — but only *called* from the macOS reader below, which is why it needs an explicit
/// allow rather than a `cfg`.
///
/// macOS gives every status item an autosave name and persists two keys under it:
/// `NSStatusItem Preferred Position <name>` (harmless — where it last sat) and
/// `NSStatusItem Visible <name>`, which is written `false` when the user ⌘-drags the item off
/// the menu bar. That second key is permanent: from then on AppKit creates the item and hides
/// it, `build()` returns `Ok`, and the app looks broken from outside while looking healthy
/// from inside.
///
/// Matched by **prefix**, not a hardcoded `Item-0`. The autosave name is generated by AppKit
/// and is not contractual — this machine has `Item-0` under two different domains. Lumen
/// creates exactly one status item, so clearing every false key is safe.
///
/// Only `Some(false)` is returned. A missing key is the normal state, and `Some(true)` is
/// already what we want; rewriting either would be churn.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub fn keys_to_clear(entries: &[(String, Option<bool>)]) -> Vec<String> {
    entries
        .iter()
        .filter(|(k, v)| k.starts_with("NSStatusItem Visible ") && *v == Some(false))
        .map(|(k, _)| k.clone())
        .collect()
}

/// A monitor's physical bounds: `(x, y, width, height)`.
pub type MonitorBounds = (f64, f64, f64, f64);

/// Where the status item actually is, as opposed to whether creating it succeeded.
#[derive(Debug, Clone, PartialEq)]
pub enum TrayPresence {
    /// On screen, in a monitor. The only state that means a user can click it.
    Present,
    /// No status-item window at all, or one with no area. `TrayIcon::rect()` returning
    /// `Ok(None)` is exactly this: on macOS it maps the status item's button's *window*, so
    /// `None` means there is no window to map — the hidden case.
    Absent,
    /// A window exists but its origin is on no monitor. A full menu bar (or a notch clip)
    /// produces this: the item is real and simply never drawn where anyone can reach it.
    /// Nothing the app can do about it, so it must be reported rather than repaired.
    OffScreen,
    /// The platform cannot answer. Linux's `rect()` always returns `None`, which is why this
    /// check is macOS-only — treating that as `Absent` would report every Linux launch as
    /// broken.
    Unknown,
}

/// Classify a status-item rect against the monitors it could be on.
///
/// Pure so it can be tested; the `rect()` call and monitor enumeration that feed it cannot be.
pub fn classify_presence(
    rect: Option<(f64, f64, f64, f64)>,
    monitors: &[MonitorBounds],
) -> TrayPresence {
    let Some((x, y, w, h)) = rect else {
        return TrayPresence::Absent;
    };
    if w <= 0.0 || h <= 0.0 {
        return TrayPresence::Absent;
    }
    // With no monitors enumerated we cannot say it is off-screen, and claiming so would turn a
    // failed query into a reported defect.
    if monitors.is_empty() {
        return TrayPresence::Unknown;
    }
    let inside = monitors
        .iter()
        .any(|&(mx, my, mw, mh)| x >= mx && y >= my && x < mx + mw && y < my + mh);
    if inside {
        TrayPresence::Present
    } else {
        TrayPresence::OffScreen
    }
}

/// The tray's state as startup and the later re-checks understand it.
#[derive(Debug, Clone, PartialEq, Default)]
pub enum TrayState {
    /// Not yet checked. Distinct from `Absent` on purpose — before `RunEvent::Ready` the
    /// event loop has not run and AppKit has not laid the status bar out, so an early check
    /// would report a false absence.
    #[default]
    Unknown,
    /// Verified on screen.
    Present,
    /// Built, but not visible. Carries the presence that was observed.
    Absent(String),
    /// Could not be built at all — the menu or the builder returned an error.
    Failed(String),
}

impl TrayState {
    /// A short line for the fault report and the UI banner.
    pub fn describe(&self) -> String {
        match self {
            TrayState::Unknown => "unknown (not yet verified)".to_string(),
            TrayState::Present => "present".to_string(),
            TrayState::Absent(why) => format!("built but not visible: {why}"),
            TrayState::Failed(why) => format!("build failed: {why}"),
        }
    }
}

/// Does the app need to reveal a window to stay reachable?
///
/// `Unknown` deliberately does **not** trigger the fallback: it is the state during startup,
/// before the status bar has been laid out, and revealing a window there would flash one open
/// on every healthy launch.
pub fn needs_fallback(tray: &TrayState) -> bool {
    matches!(tray, TrayState::Absent(_) | TrayState::Failed(_))
}

/// Everything that went wrong during startup, and the tray's verified state.
///
/// Managed as Tauri state so the frontend banner, the fault reporter and the later tray
/// re-checks all read one source rather than three guesses.
#[derive(Default)]
pub struct StartupHealth {
    degradations: Mutex<Vec<String>>,
    tray: Mutex<TrayState>,
    /// Set once a "the tray is missing" line has been logged, so `update_tray` — which runs on
    /// every daemon snapshot — reports it once instead of every second.
    warned_missing_tray: AtomicBool,
    /// Set once the restored-icon explanation has been shown, so it appears on the launch that
    /// repaired the preference and not on every launch after it.
    explained_restore: AtomicBool,
}

impl StartupHealth {
    /// Record a step that failed without aborting startup.
    pub fn degrade(&self, step: &str, detail: impl std::fmt::Display) {
        let line = format!("{step}: {detail}");
        log::error!("DEGRADED {line}");
        if let Ok(mut v) = self.degradations.lock() {
            v.push(line);
        }
    }

    pub fn set_tray(&self, state: TrayState) {
        if let Ok(mut t) = self.tray.lock() {
            *t = state;
        }
    }

    pub fn tray(&self) -> TrayState {
        self.tray.lock().map(|t| t.clone()).unwrap_or_default()
    }

    pub fn degradations(&self) -> Vec<String> {
        self.degradations
            .lock()
            .map(|v| v.clone())
            .unwrap_or_default()
    }

    /// True the first time only. Used for the once-per-process log lines.
    pub fn claim_missing_tray_warning(&self) -> bool {
        !self.warned_missing_tray.swap(true, Ordering::Relaxed)
    }

    pub fn claim_restore_explanation(&self) -> bool {
        !self.explained_restore.swap(true, Ordering::Relaxed)
    }

    /// Is anything wrong? Drives whether the frontend shows a banner at all — it must stay
    /// silent on a healthy launch.
    pub fn is_degraded(&self) -> bool {
        !self.degradations().is_empty() || needs_fallback(&self.tray())
    }
}

/// How the tray check should be forced, for testing paths that cannot otherwise be reached.
///
/// Honoured **in release builds too**. `TrayIconBuilder::build`, `rect()` and `setVisible`
/// need a live app and a real menu bar, so there is no unit test that can reach the failure
/// branches — and "somehow break your menu bar" is not a repeatable manual test. This makes
/// each branch reachable deliberately.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum SimulatedTray {
    None,
    BuildError,
    Absent,
    OffScreen,
}

pub fn simulated_tray_from(env: Option<&str>) -> SimulatedTray {
    match env.map(|s| s.trim().to_ascii_lowercase()).as_deref() {
        Some("err") | Some("error") => SimulatedTray::BuildError,
        Some("absent") => SimulatedTray::Absent,
        Some("offscreen") => SimulatedTray::OffScreen,
        _ => SimulatedTray::None,
    }
}

/// Read the `NSStatusItem *` preferences, log every one found, and clear the keys that hide
/// our status item. Returns the keys cleared.
///
/// Called *before* `TrayIconBuilder::build`, so the item is created visible in the first place
/// — no flicker, and no repair round-trip. Logging every key (not only the cleared ones) means
/// the field diagnostic for the next report comes back for free.
#[cfg(target_os = "macos")]
pub fn clear_hidden_status_item_prefs() -> Vec<String> {
    use objc2_foundation::{NSString, NSUserDefaults};

    // No `unsafe` needed: objc2's NSUserDefaults accessors are safe wrappers.
    let mut found: Vec<(String, Option<bool>)> = Vec::new();
    {
        let defaults = NSUserDefaults::standardUserDefaults();
        let dict = defaults.dictionaryRepresentation();
        for key in dict.keys() {
            let k = key.to_string();
            if !k.starts_with("NSStatusItem ") {
                continue;
            }
            // Only the `Visible` keys are booleans. `Preferred Position` holds a number — 612 on
            // this machine — and `boolForKey` on it returns true, so reading every key as a bool
            // logged `Preferred Position = Some(true)`, which is meaningless and would send a
            // maintainer down the wrong path. `keys_to_clear` was never fooled (it filters on the
            // prefix), but the log line is the diagnostic a human reads.
            let is_visible_key = k.starts_with("NSStatusItem Visible ");
            // `objectForKey` distinguishes "absent" from "present and false"; `boolForKey` alone
            // would render both as false and we would clear keys that do not exist.
            let present = dict.objectForKey(&NSString::from_str(&k)).is_some();
            let val = if is_visible_key && present {
                Some(defaults.boolForKey(&NSString::from_str(&k)))
            } else {
                None
            };
            if is_visible_key {
                log::warn!("TRAY: pref {k} = {val:?}");
            } else {
                log::warn!("TRAY: pref {k} present (not a visibility flag)");
            }
            found.push((k, val));
        }

        let to_clear = keys_to_clear(&found);
        for key in &to_clear {
            log::warn!("TRAY: clearing {key} — the icon was hidden by a previous ⌘-drag");
            defaults.removeObjectForKey(&NSString::from_str(key));
        }
        to_clear
    }
}

#[cfg(not(target_os = "macos"))]
pub fn clear_hidden_status_item_prefs() -> Vec<String> {
    // The autosave mechanism is AppKit's. Nothing to do elsewhere.
    Vec::new()
}

/// Build the tray menu items.
///
/// Extracted so the caller can degrade instead of propagating. As three `?` in `setup()` these
/// aborted Tauri startup outright, leaving a process with no window, no tray and no way in —
/// and the fallback added in 1.5.1 wrapped only the *builder* result, so it covered none of
/// them.
pub fn build_tray_menu_items(app: &tauri::App) -> tauri::Result<tauri::menu::Menu<tauri::Wry>> {
    use tauri::menu::{Menu, MenuItem};
    let quit = MenuItem::with_id(app, "quit", "Quit Lumen", true, None::<&str>)?;
    let show = MenuItem::with_id(app, "show", "Open Lumen", true, None::<&str>)?;
    Menu::with_items(app, &[&show, &quit])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_log_level_defaults_differ_by_profile_but_are_never_off() {
        // The whole point of B1: a release build must still log. `Off` by default is what made
        // issue #5 undiagnosable, so it must not be reachable without asking for it.
        assert_eq!(log_level_from(None, false), log::LevelFilter::Warn);
        assert_eq!(log_level_from(None, true), log::LevelFilter::Info);
    }

    #[test]
    fn the_log_level_is_parsed_case_and_space_insensitively() {
        for (raw, want) in [
            ("off", log::LevelFilter::Off),
            ("ERROR", log::LevelFilter::Error),
            ("Warn", log::LevelFilter::Warn),
            ("warning", log::LevelFilter::Warn),
            (" info ", log::LevelFilter::Info),
            ("debug", log::LevelFilter::Debug),
            ("TRACE", log::LevelFilter::Trace),
        ] {
            assert_eq!(log_level_from(Some(raw), false), want, "parsing {raw:?}");
        }
    }

    #[test]
    fn an_unparseable_log_level_falls_back_rather_than_silencing_the_app() {
        // A typo must not be the difference between having a diagnostic and not having one.
        assert_eq!(
            log_level_from(Some("verbose"), false),
            log::LevelFilter::Warn
        );
        assert_eq!(log_level_from(Some(""), true), log::LevelFilter::Info);
    }

    fn pref(k: &str, v: Option<bool>) -> (String, Option<bool>) {
        (k.to_string(), v)
    }

    #[test]
    fn only_the_visible_false_status_item_keys_are_cleared() {
        let entries = vec![
            // The real shape observed on this machine: a position key with no visible key.
            pref("NSStatusItem Preferred Position Item-0", None),
            pref("NSStatusItem Visible Item-0", Some(false)),
            pref("NSStatusItem Visible Item-1", Some(true)),
            pref("NSStatusItem Visible Item-2", None),
            pref("SomethingElse", Some(false)),
        ];
        assert_eq!(
            keys_to_clear(&entries),
            vec!["NSStatusItem Visible Item-0".to_string()]
        );
    }

    #[test]
    fn the_autosave_name_is_matched_by_prefix_not_hardcoded() {
        // AppKit generates the name and it is not contractual — this machine has Item-0 under
        // two different domains. Hardcoding it would miss any other name.
        let entries = vec![
            pref("NSStatusItem Visible lumen-tray", Some(false)),
            pref("NSStatusItem Visible Item-7", Some(false)),
        ];
        let got = keys_to_clear(&entries);
        assert_eq!(got.len(), 2, "both names should be cleared, got {got:?}");
    }

    #[test]
    fn a_healthy_machine_has_nothing_to_clear() {
        let entries = vec![pref("NSStatusItem Preferred Position Item-0", None)];
        assert!(keys_to_clear(&entries).is_empty());
    }

    const SCREEN: MonitorBounds = (0.0, 0.0, 1920.0, 1080.0);

    #[test]
    fn a_rect_inside_a_monitor_is_present() {
        assert_eq!(
            classify_presence(Some((1600.0, 0.0, 24.0, 24.0)), &[SCREEN]),
            TrayPresence::Present
        );
    }

    #[test]
    fn no_rect_is_absent_because_that_is_what_a_hidden_status_item_reports() {
        // TrayIcon::rect() maps the status item button's *window*; Ok(None) means there is no
        // window, which is exactly the persisted-hidden case this whole module is about.
        assert_eq!(classify_presence(None, &[SCREEN]), TrayPresence::Absent);
    }

    #[test]
    fn a_zero_area_rect_is_absent_not_present() {
        assert_eq!(
            classify_presence(Some((1600.0, 0.0, 0.0, 24.0)), &[SCREEN]),
            TrayPresence::Absent
        );
        assert_eq!(
            classify_presence(Some((1600.0, 0.0, 24.0, 0.0)), &[SCREEN]),
            TrayPresence::Absent
        );
    }

    #[test]
    fn a_rect_on_no_monitor_is_offscreen_which_is_the_full_menu_bar_case() {
        assert_eq!(
            classify_presence(Some((4000.0, 0.0, 24.0, 24.0)), &[SCREEN]),
            TrayPresence::OffScreen
        );
    }

    #[test]
    fn a_rect_on_a_second_monitor_is_still_present() {
        let secondary = (1920.0, -200.0, 1280.0, 800.0);
        assert_eq!(
            classify_presence(Some((2400.0, -180.0, 24.0, 24.0)), &[SCREEN, secondary]),
            TrayPresence::Present
        );
    }

    #[test]
    fn unenumerable_monitors_are_unknown_rather_than_a_reported_defect() {
        // Failing to enumerate monitors is our ignorance, not the user's broken menu bar.
        assert_eq!(
            classify_presence(Some((1600.0, 0.0, 24.0, 24.0)), &[]),
            TrayPresence::Unknown
        );
    }

    #[test]
    fn the_fallback_fires_for_absent_and_failed_but_never_for_unknown() {
        assert!(needs_fallback(&TrayState::Absent("hidden".into())));
        assert!(needs_fallback(&TrayState::Failed("boom".into())));
        assert!(!needs_fallback(&TrayState::Present));
        // Unknown is the startup state. Revealing a window there would flash one open on
        // every healthy launch.
        assert!(!needs_fallback(&TrayState::Unknown));
    }

    #[test]
    fn a_healthy_startup_is_not_degraded_so_the_banner_stays_hidden() {
        let h = StartupHealth::default();
        h.set_tray(TrayState::Present);
        assert!(!h.is_degraded());
        assert!(h.degradations().is_empty());
    }

    #[test]
    fn a_recorded_degradation_makes_the_app_report_itself_degraded() {
        let h = StartupHealth::default();
        h.set_tray(TrayState::Present);
        h.degrade("daemon", "sidecar lumen-daemon not found");
        assert!(h.is_degraded());
        assert_eq!(
            h.degradations(),
            vec!["daemon: sidecar lumen-daemon not found".to_string()]
        );
    }

    #[test]
    fn an_invisible_tray_alone_is_enough_to_be_degraded() {
        // The issue #5 shape: nothing errored, so there are no degradations — but the app is
        // still unusable, and `is_degraded` has to say so.
        let h = StartupHealth::default();
        h.set_tray(TrayState::Absent("hidden by preference".into()));
        assert!(h.degradations().is_empty());
        assert!(h.is_degraded());
    }

    #[test]
    fn the_once_only_claims_are_true_exactly_once() {
        // update_tray runs on every daemon snapshot; without this it would log every second.
        let h = StartupHealth::default();
        assert!(h.claim_missing_tray_warning());
        assert!(!h.claim_missing_tray_warning());
        assert!(h.claim_restore_explanation());
        assert!(!h.claim_restore_explanation());
    }

    #[test]
    fn tray_states_describe_themselves_for_the_report() {
        assert_eq!(TrayState::Present.describe(), "present");
        assert!(TrayState::Absent("hidden".into())
            .describe()
            .contains("not visible"));
        assert!(TrayState::Failed("boom".into()).describe().contains("boom"));
    }

    #[test]
    fn the_tray_simulation_env_var_is_parsed() {
        assert_eq!(simulated_tray_from(None), SimulatedTray::None);
        assert_eq!(simulated_tray_from(Some("err")), SimulatedTray::BuildError);
        assert_eq!(simulated_tray_from(Some("ABSENT")), SimulatedTray::Absent);
        assert_eq!(
            simulated_tray_from(Some(" offscreen ")),
            SimulatedTray::OffScreen
        );
        assert_eq!(simulated_tray_from(Some("nonsense")), SimulatedTray::None);
    }
}
